parameters:
- name: sourceDirectory
  type: string
  default: false

- name: serviceName
  type: string
  default: false

- name: mainBranch
  type: string
  default: false

- name: prBranch
  type: string
  default: false

- name: gitUserEmail
  type: string
  default: false

- name: gitUserName
  type: string
  default: false

- name: buildCommand
  type: string
  default: build

- name: lintCommand
  type: string
  default: lint

- name: runtimeVersion
  type: string
  default: false

jobs:
- template: ../common/template.yml@cloud-shell
  parameters:
    mainBranch: ${{ parameters.mainBranch }}
    prBranch: ${{ parameters.prBranch }}
    gitUserEmail: ${{ parameters.gitUserEmail }}
    gitUserName: ${{ parameters.gitUserName }}
    serviceName: ${{ parameters.serviceName }}
    usersteps:
    - ${{ if ne(parameters.runtimeVersion, false) }}:
      - task: NodeTool@0
        inputs:
          versionSpec: ${{ parameters.runtimeVersion }} 
    - bash: |
        echo "npm install" && npm install || exit 1
        echo "npm run ${{ parameters.buildCommand }}" && npm run ${{ parameters.buildCommand }} || exit 1
        echo "npm run ${{ parameters.lintCommand }}" && npm run ${{ parameters.lintCommand }} || exit 1
      workingDirectory: ${{ parameters.sourceDirectory }}
      displayName: Build and Lint Specification