version: 0.2

phases:
  build:
    commands:
      - SYSTEM_DEPS="python python-pip groff gawk jq"
      - PYTHON_DEPS="awscli"
      - ARTIFACT_TYPE="or"
      - echo "${VERSION}" | grep 'notset' && exit 1 || echo "Version is set to - ${VERSION}"
      - echo "Building Official Release Artifact from git tag version - ${VERSION}"
      - apt-get update && apt-get install -y ${SYSTEM_DEPS}
      - pip install ${PYTHON_DEPS}
      - echo "ARTIFACT = ${VERSION}, PRNUMBER=${PRNUMBER}, and VERSION=${VERSION}"
      - git config --global hub.protocol https
      - git config --global user.email $GITHUB_USER_EMAIL
      - git config --global user.name $GITHUB_USERNAME
      - git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${APP_REPO}"
      - git fetch --tags
      - git checkout "refs/tags/${VERSION}"
      - npm install
      - HUSKY_SKIP_INSTALL=1 npm run build && npm run test
      - aws s3api put-object --bucket ${ARTIFACT_S3_BUCKET} --key ${APP_NAME}-${ARTIFACT_TYPE}-${VERSION}/
      - aws s3 cp ${ARTIFACT_FILE} s3://${ARTIFACT_S3_BUCKET}/${APP_NAME}-${ARTIFACT_TYPE}-${VERSION}/
